name: GitHub Actions Demo
run-name: diplom deploy
on: push
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      #- run: helm upgrade --install --namespace default wordpress ./wordpress --set tag=
      - run: echo "test depoy"