name: GitHub Actions Demo
run-name: diplom deploy
on: push
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main'
      - run: helm upgrade --install --namespace default wordpress ./wordpress --set tag=v0.0.12
      - run: chmod +x check.sh && ./check.sh