name: GitHub Actions Demo
run-name: diplom deploy
on: push
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: helm upgrade --install --namespace default wordpress ./wordpress --set tag=v0.0.10
      - run: chmod +x check.sh && ./check.sh